#!/bin/sh

conect="📶"
disconect="❌"
unknown="📡"

wifi="$(cat /sys/class/net/wlan0/operstate)"


if [ "$wifi" = "up" ];
then
	echo $conect
elif [ "$wifi" = "down" ];
then
    echo $disconect
elif [ "$wifi" = "unknown" ];
then
	echo $unknown

fi    	
